import {
	SiXdadevelopers,
	SiHtml5,
	SiJavascript,
	SiCss3,
	SiTailwindcss,
	SiBuefy,
	SiBulma,
	SiVuetify,
	SiBootstrap,
	SiApacheecharts,
	SiLodash,
	SiVuedotjs,
	SiReact,
	SiNextdotjs,
	SiNodedotjs,
	SiJava,
	SiSpringboot,
	SiHibernate,
	SiPython,
	SiDjango,
	SiPostgresql,
	SiOracle,
	SiMicrosoftsqlserver,
	SiSqlite,
	SiApollographql,
	SiMongodb,
	SiDocker,
	SiNginx,
	SiApachekafka,
	SiJsonwebtokens,
} from 'react-icons/si';
import { CgDatabase, CgCodeSlash, CgLogIn } from 'react-icons/cg';
import { AiOutlineCode } from 'react-icons/ai';

const logoMapper = {
	CgCodeSlash: <CgCodeSlash />,
	SiXdadevelopers: <SiXdadevelopers />,
	CgDatabase: <CgDatabase />,
	AiOutlineCode: <AiOutlineCode />,
	SiVuedotjs: <SiVuedotjs />,
	SiJavascript: <SiJavascript />,
	SiHtml5: <SiHtml5 />,
	SiCss3: <SiCss3 />,
	SiTailwindcss: <SiTailwindcss />,
	SiBuefy: <SiBuefy />,
	SiBulma: <SiBulma />,
	SiVuetify: <SiVuetify />,
	SiBootstrap: <SiBootstrap />,
	SiApacheecharts: <SiApacheecharts />,
	SiLodash: <SiLodash />,
	SiReact: <SiReact />,
	SiNextdotjs: <SiNextdotjs />,
	SiNodedotjs: <SiNodedotjs />,
	SiJava: <SiJava />,
	SiSpringboot: <SiSpringboot />,
	SiHibernate: <SiHibernate />,
	SiPython: <SiPython />,
	SiDjango: <SiDjango />,
	SiPostgresql: <SiPostgresql />,
	SiOracle: <SiOracle />,
	SiMicrosoftsqlserver: <SiMicrosoftsqlserver />,
	SiSqlite: <SiSqlite />,
	SiApollographql: <SiApollographql />,
	SiMongodb: <SiMongodb />,
	SiDocker: <SiDocker />,
	SiNginx: <SiNginx />,
	SiApachekafka: <SiApachekafka />,
	CgLogIn: <CgLogIn />,
	SiJsonwebtokens: <SiJsonwebtokens />,
};

export default logoMapper;
